language: node_js

node_js:
  - 12
  - 10
  - 8

branches:
  only:
    - master

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
    - stage: coverage
      node_js: lts/*
      script:
        - npm run coverage

stages:
  - test
  - coverage
  - release
